### ISSUE TITLE
question(not issue)

### ISSUE THREAD

**Issue by fipoucat** [jernejjevsenak/dendroTools#1]
@jernejjevsenak I discovered your package I think more related to paleo climate studies. This is quite interesting and then wonder if it is possible to use your metrics for present and future climate from observation and climate model.

**Comment by jernejjevsenak** [comment]
@fipoucat, Thank you for your question. In general, dendroTools can be used to study the effect of day-scale climate parameters on tree ring parameters, such as tree ring widths. In general, you could then use the established models to simulate the effects of future climate. However, this is not implemented in the dendroTools, but should be coded independently. 
Alternatively, If you have the future climate scenarios, you can also use them as input data (argument env_data) and investigate the effects directly. I hope this answers your question.

**Comment by fipoucat** [comment]
Thank you very much.
